// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $dostawa from "./routes/dostawa.tsx";
import * as $index from "./routes/index.tsx";
import * as $kategorie from "./routes/kategorie.tsx";
import * as $kategorie_slug_ from "./routes/kategorie/[slug].tsx";
import * as $kontakt from "./routes/kontakt.tsx";
import * as $platnosci from "./routes/platnosci.tsx";
import * as $polityka_prywatnosci from "./routes/polityka-prywatnosci.tsx";
import * as $produkty from "./routes/produkty.tsx";
import * as $produkty_slug_ from "./routes/produkty/[slug].tsx";
import * as $regulamin from "./routes/regulamin.tsx";
import * as $NewsletterPopup from "./islands/NewsletterPopup.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/blog.tsx": $blog,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/dostawa.tsx": $dostawa,
    "./routes/index.tsx": $index,
    "./routes/kategorie.tsx": $kategorie,
    "./routes/kategorie/[slug].tsx": $kategorie_slug_,
    "./routes/kontakt.tsx": $kontakt,
    "./routes/platnosci.tsx": $platnosci,
    "./routes/polityka-prywatnosci.tsx": $polityka_prywatnosci,
    "./routes/produkty.tsx": $produkty,
    "./routes/produkty/[slug].tsx": $produkty_slug_,
    "./routes/regulamin.tsx": $regulamin,
  },
  islands: {
    "./islands/NewsletterPopup.tsx": $NewsletterPopup,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
